config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :items, only: [:index, :show, :new]
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw', as: 'confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :index, :show, :create, :confirm, :complete] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :email, :postal_code, :address, :telephone_unmber, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>
  <div clss="row">
    <div class="col-xs-12">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>

        <div>
          <p>会員ID <%= @customer.id %></p>
          <p>氏名 <%= f.text_field :last_name %> <%= f.text_field :first_name %></p>
          <p>フリガナ <%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></p>
          <p>郵便番号 <%= f.text_field :postal_code %></p>
          <p>住所 <%= f.text_area :address %></p>
          <p>電話番号 <%= f.text_field :telephone_number %></p>
          <p>メールアドレス <%= f.text_field :email %></p>
          <p>
            会員ステータス
            <%= f.radio_button :is_deleted, "false" %>
            <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, "true" %>
            <%= f.label :is_deleted, "退会" %>
          </p>
        </div>
        <%= f.submit "変更を保存", class: "btn btn-success" %>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h3>会員一覧</h3>
  <div class="center-block">
    <div class="col-xs-1">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
          <tbody>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer.id) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == false %>
                  有効
                <% else %>
                  退会
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
  <div class="center-block">
    <div>
      <div class="col-xs-7">
        <p>会員ID <%= @customer.id %></p>
        <p>氏名 <%= @customer.last_name %> <%= @customer.first_name %></p>
        <p>フリガナ <%= @customer.last_name_kana %> <%= @customer.first_name_kana %></p>
        <p>郵便番号 <%= @customer.postal_code %></p>
        <p>住所 <%= @customer.address %></p>
        <p>電話番号 <%= @customer.telephone_number %></p>
        <p>メールアドレス <%= @customer.email %></p>
        <p>
          会員ステータス
          <% if @customer.is_deleted == false %>
            有効
          <% else %>
            退会
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <span><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %></span>
  <span><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %></span>
</div>