config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :items, only: [:index, :show, :new]
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw', as: 'confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :index, :show, :create, :confirm, :complete] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum method_of_payment: { credit_card: 0, transfer: 1 }

  belongs_to :customer
  has_many :items, through: :order_details
  has_many :order_details
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h3>注文履歴詳細</h3>
  <div class="center-block">
    <div class="row">
      <div class="col-md-8">
        <p>
          購入者
          <%= link_to admin_customer_path(@order.customer_id) do %>
            <%= @order.delivery_name %>
          <% end %>
        </p>
        <p>注文日 <%= @order.created_at.strftime('%Y/%m/%d') %></p>
        <p>
          配送先
          〒<%= @order.shipping_postal_code %>
          <%= @order.shipping_adddress %><br>
          <%= @order.delivery_name %>
        </p>
        <p>支払方法 <%= @order.method_of_payment_i18n %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <table class="order-show-table table">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
          </thead>
          <% @order_details.each do |order_detail| %>
            <tbody>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= order_detail.item.with_tax_price %></td>
                <td><%= order_detail.amount %></td>
                <td><%= order_detail.subtotal %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
      <div class="col-xs-4">
        <table class="text-right">
         <tr>
          <tr>
            <th>商品合計</th>
            <td><%= (@order.payment_amount - @order.postage).to_s(:delimited) %></td>
          </tr>
          <tr>
            <th>送料</th>
            <% @order.postage = 800 %>
            <td><%= @order.postage %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td><%= @order.payment_amount.to_s(:delimited) %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>